#ifndef __QRCKWATCH_RPTOCOL_H_INCLUDED__
#define __QRCKWATCH_RPTOCOL_H_INCLUDED__

enum Message
{
	MSG_NOTIFICATIONS_BITMASK 	= 0, 
	MSG_CHARGE_LEVEL	= 1,
	MSG_WEATHER_ALERT	= 2,
	MSG_REQUEST_ALL		= 100, // ask to send all the possible updates - sent on the start of the watchface
};

enum Notifications 
{
	NOTIFICATION_UNKNOWN 	= 0X01,
	NOTIFICATION_CALENDAR 	= 0X02,
	NOTIFICATION_GOOGLEHANGOUTS	= 0X04,
	NOTIFICATION_GOOGLEPLUS	= 0x08,
	NOTIFICATION_MESSAGES	= 0X10,
	NOTIFICATION_EMAIL	= 0X20,
	NOTIFICATION_GMAIL	= 0X40,
	NOTIFICATION_PHONE	= 0X80,
	NOTIFICATION_SKYPE	= 0X100,
	NOTIFICATION_VOIP	= 0X200,
	NOTIFICATION_IM	= 0X400,
	NOTIFICATION_FACEBOOK	= 0X800,
	NOTIFICATION_LINKEDIN	= 0X1000,
	NOTIFICATION_VK	= 0X2000,
	NOTIFICATION_INSTGRAM = 0X4000
};

#endif
